# -*- coding: utf-8 -*-
#
# KDDart Docs documentation build configuration file, created by
# sphinx-quickstart on Sat Sep  3 21:32:27 2016.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
# DH1  import sphinx_bootstrap_theme

import sys, os, datetime, pytz # DH3
import sphinx_rtd_theme # DH1

sys.path.insert(0, os.path.abspath('.')) # DH3


# DH1  Customisations to conf.py
# DH1
# DH1 10 Oct 2016 - 1st iteration of changes
# DH2 19 Jan 2017 -  added 'sphinxcontrib.images' to extensions
# DH3 14 Mar 2018 - Added support for Reauthoring Toolkit to "create Liquid HTML Active Learning Resources"
#                   which originated here: https://latte.ee.usyd.edu.au/Reauthoring/
# DH4 10-18 Apr 2019 Fixes for LatexPDF generation which also included adding of the
#                    copyright info for back of cover page of PDF which requires
#                    Sphinx 1.8.3. Note that sort issues now work fine with this version.

# DH1

# Activate the theme.
# DH1  html_theme = 'bootstrap'
# DH1  html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()

# Javascript files - added for Matomo analytics 2022/05/19
html_js_files = [
    'js/matomos.js',
]

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

global_data_context = '' # @@NAME YOUR CONTEXT@@ # DH3
global_data_entry_url = '' # @@URL TO COLLECT DATA@@ # DH3
global_data_entry_method = 'POST' # DH3
global_data_subject_field_name = 'leco_subject_field' # DH3
global_data_verb_field_name =    'leco_verb_field' # DH3
global_data_object_field_name =  'leco_object_field' # DH3
global_data_context_field_name = 'leco_context_field' # DH3



# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.ifconfig',
    'sphinxcontrib.images',
    'sphinx.ext.ifconfig', # DH3
    'sphinx.ext.mathjax', # DH3
    'Sphinx_ext.activityduration', # DH3
    'Sphinx_ext.htmlform', # DH3
    'Sphinx_ext.instructorfeedback', # DH3
    'Sphinx_ext.eqt',  # DH3
    'Sphinx_ext.instructorguide', # DH3
    'Sphinx_ext.embeddedvideo', # DH3
    'Sphinx_ext.xy_click', # DH3
    'Sphinx_ext.questions', # DH3
    'Sphinx_ext.iframe', # DH3
    'sphinxcontrib.images', # DH3

]
# DH2 - added 'sphinxcontrib.images' to extensions


# E_QUESTION EXTENSION CONF # DH3
#
eqt_action = global_data_entry_url # DH3
eqt_id_field_name = global_data_verb_field_name # DH3
eqt_data_field_name = 'equestion_name' # DH3

#
# INSTRUCTOR-FEEDBACK EXTENSION CONF # DH3
#
instructor_feedback_columns = '60' # DH3




# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The encoding of source files.
#
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'KDSmart Documentation'
copyright = u'2020, Diversity Arrays Technology P/L'
copyright2 = u'Copyright 2019 - Diversity Arrays Technology Pty Ltd'
author = u'Diversity Arrays Technology'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'3.2.4'
# The full version, including alpha/beta/rc tags.
release = u'3.2.4'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#
# today = ''
#
# Else, today_fmt is used as the format for a strftime call.
#
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all
# documents.
#
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for images_config ----------------------------------------------

images_config = {}


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# html_theme = 'alabaster'

html_theme = "sphinx_rtd_theme"  # DH1

html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]  # DH1
html_style = 'learning_resources.css' # DH3

def setup(app):
    app.add_css_file('css/kdd_theme.css')

# html_style = 'css/kdmanage_theme.css'  # DH1
html_theme_options = {'collapse_navigation': False}  # DH1
using_rtd_theme = True  # DH1

# DH1 Note: The kdmanage_theme.css is a copy of the default rtd theme.css file which
# DH1       will overwrite the default css file. The kdmanage_theme.css file
# DH1       needs to be placed in the source/_static/css folder from where
# DH1       it is copied by the build into the build/html/_static/css folder
# DH1
# DH1       Minor changes to the Read the Docs Theme default file 'theme.css'
# DH1       Changes:
# DH1        1. Colours from #2980B9 to #73879C (to match the colour used in KDManage)
# DH1        2. Removed white-space:nowrap from tables to allow text to remain in view
# DH1           and not need to scroll right/left to view
# DH1
# DH1
# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom themes here, relative to this directory.
# html_theme_path = []

# The name for this set of Sphinx documents.
# "<project> v<release> documentation" by default.
#
# html_title = u'KDDart Docs v1'

# A shorter title for the navigation bar.  Default is the same as html_title.
#
# html_short_title = None
html_short_title = 'KDSmart Help' # DH1

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
#
# html_logo = None

html_logo = '../../commonimages/kdsmart_400x160.png' # DH1

# The name of an image file (relative to this directory) to use as a favicon of
# the docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#
# html_favicon = None

html_favicon = '../../commonimages/kdsmart_logo.ico' # DH1

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#
# html_extra_path = []

# If not None, a 'Last updated on:' timestamp is inserted at every page
# bottom, using the given strftime format.
# The empty string is equivalent to '%b %d, %Y'.
#
html_last_updated_fmt = '%d %b, %Y'  #DH1

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
#
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#
# html_additional_pages = {}

# If false, no module index is generated.
#
# html_domain_indices = True

# If false, no index is generated.
#
# html_use_index = True

# If true, the index is split into individual pages for each letter.
#
# html_split_index = False

# If true, links to the reST sources are added to the pages.
#
# html_show_sourcelink = True
html_show_sourcelink = False # DH1

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#
html_show_copyright = True  # DH1

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr', 'zh'
#
html_search_language = 'en' # DH1

# A dictionary with options for the search language support, empty by default.
# 'ja' uses this config value.
# 'zh' user can custom change `jieba` dictionary path.
#
# html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#
# html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = 'KDSmartDocs'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
# The paper size ('letterpaper' or 'a4paper').
#
# 'figure_align': 'htbp', # DH4 - Set to 'H' to prevent floating images and moved above
# as in this position it broke the build for some very strange reason. Multiple
# attempts did not make it work.
# 'papersize': 'letterpaper',
'figure_align': 'H', # DH4 Moved to this position (see the note just above)
'papersize': 'a4',# DH1

# necessary for unicode characters in pdf output
'inputenc': '',
'utf8extra': '',

# remove blank pages (between the title page and the TOC, etc.)
'classoptions': ',openany,oneside',
'babel' : '\\usepackage[english]{babel}',

# Additional stuff for the LaTeX preamble.
# DH4: Introduced the new sphinxbackoftitlepage from 1.8.3 onwards
# DH4: Implimented the Copyright a bit messily and can be improved.
#
'preamble': r'''
\newcommand\sphinxbackoftitlepage{%
     This user guide is \\
     Copyright: 2019 - DArT - Diversity Arrays Technology Pty Ltd \\
     \\
     All rights reserved. No part of this User Guide may be\\
     reporduced without permission of the copyright owner.\\ \\ \\
     Contact Us\\
     Email: kdsmart@diversityarrays.com\\ \\
     Address: Building 3, Level D, University of Canberra, \\
              Monana St., Bruce, ACT 2617, Australia\\ \\
     Postal:  LPO Box 5067, \\
              Bruce ACT 2617, Australia\\
     \par}
  \usepackage{hyperref}
  \setcounter{tocdepth}{3}
'''
# The font size ('10pt', '11pt' or '12pt').
#
# 'pointsize': '10pt',
# Additional stuff for the LaTeX preamble.
#
# 'preamble': '',
# Latex figure (float) alignment
#
# 'figure_align': 'htbp', # DH4 - Set to 'H' to prevent floating images and moved above
# as in this position it broke the build for some very strange reason. Multiple
# attempts did not make it work.
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
# This Title appears at top 8 Sept 2016
latex_documents = [
    (master_doc, 'KDSmart.tex', u'KDSmart Documentation',
     u'DArT Team', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#


latex_logo = '../../commonimages/kdsmart_400x160.png'  # DH1


# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
#
# latex_use_parts = False

# If true, show page references after internal links.
#
# latex_show_pagerefs = False
latex_use_parts = False # DH1

# If true, show URL addresses after external links.
#
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
#
# latex_appendices = []

# It false, will not define \strong, \code, 	itleref, \crossref ... but only
# \sphinxstrong, ..., \sphinxtitleref, ... To help avoid clash with user added
# packages.
#
# latex_keep_old_macro_names = True

# If false, no module index is generated.
#
# latex_domain_indices = True




# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'kdsmartdocs', u'KDSmart Documentation',
     [author], 1)
]

# If true, show URL addresses after external links.
#
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'KDSmartDocs', u'KDSmart Documentation',
     'DArT Team', 'KDSmartDocs', 'KDSmart Documentation Collection',
     'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
#
# texinfo_appendices = []

# If false, no module index is generated.
#
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
#
# texinfo_no_detailmenu = False


# -- Options for Epub output ----------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# The basename for the epub file. It defaults to the project name.
# epub_basename = project

# The HTML theme for the epub output. Since the default themes are not
# optimized for small screen space, using the same theme for HTML and epub
# output is usually not wise. This defaults to 'epub', a theme designed to save
# visual space.
#
# epub_theme = 'epub'

# The language of the text. It defaults to the language option
# or 'en' if the language is not set.
#
# epub_language = ''

# The scheme of the identifier. Typical schemes are ISBN or URL.
# epub_scheme = ''

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A tuple containing the cover image and cover page html template filenames.
#
# epub_cover = ()

# A sequence of (type, uri, title) tuples for the guide element of content.opf.
#
# epub_guide = ()

# HTML files that should be inserted before the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#
# epub_pre_files = []

# HTML files that should be inserted after the pages created by sphinx.
# The format is a list of tuples containing the path and title.
#
# epub_post_files = []

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# The depth of the table of contents in toc.ncx.
#
# epub_tocdepth = 3

# Allow duplicate toc entries.
#
# epub_tocdup = True

# Choose between 'default' and 'includehidden'.
#
# epub_tocscope = 'default'

# Fix unsupported image types using the Pillow.
#
# epub_fix_images = False

# Scale large images.
#
# epub_max_image_width = 0

# How to display URL addresses: 'footnote', 'no', or 'inline'.
#
# epub_show_urls = 'inline'

# If false, no index is generated.
#
# epub_use_index = True


# -- Options for PDF output --------------------------------------------------
# Grouping the document tree into PDF files. List of tuples
# (source start file, target name, title, author, options).
#
# If there is more than one author, separate them with \\.
# For example: r'Guido van Rossum\\Fred L. Drake, Jr., editor'
#
# The options element is a dictionary that lets you override
# this config per-document.
# For example,
# ('index', u'MyProject', u'My Project', u'Author Name',
# dict(pdf_compressed = True))
# would mean that specific document would be compressed
# regardless of the global pdf_compressed setting.
pdf_documents = [
 ('index', u'MyProject', u'My Project', u'Author Name'),
]
# A comma-separated list of custom stylesheets. Example:
pdf_stylesheets = ['sphinx','kerning','a4']
# A list of folders to search for stylesheets. Example:
pdf_style_path = ['.', '_styles']
# Create a compressed PDF
# Use True/False or 1/0
# Example: compressed=True
#pdf_compressed = False
# A colon-separated list of folders to search for fonts. Example:
# pdf_font_path = ['/usr/share/fonts', '/usr/share/texmf-dist/fonts/']
# Language to be used for hyphenation support
#pdf_language = "en_US"
# Mode for literal blocks wider than the frame. Can be
# overflow, shrink or truncate
pdf_fit_mode = "shrink"
# Section level that forces a break page.
# For example: 1 means top-level sections start in a new page
# 0 means disabled
pdf_break_level = 1
# When a section starts in a new page, force it to be 'even', 'odd',
# or just use 'any'
#pdf_breakside = 'any'
# Insert footnotes where they are defined instead of
# at the end.
#pdf_inline_footnotes = True
# verbosity level. 0 1 or 2
#pdf_verbosity = 0
# If false, no index is generated.
# pdf_use_index = True
# If false, no modindex is generated.
#pdf_use_modindex = True
# If false, no coverpage is generated.
pdf_use_coverpage = False
# Name of the cover page template to use
#pdf_cover_template = 'sphinxcover.tmpl'
# Documents to append as an appendix to all manuals.
#pdf_appendices = []
# Enable experimental feature to split table cells. Use it
# if you get "DelayedTable too big" errors
pdf_splittables = True # DH4 - Testing a True setting
# Set the default DPI for images
#pdf_default_dpi = 72
# Enable rst2pdf extension modules (default is only vectorpdf)
# you need vectorpdf if you want to use sphinx's graphviz support
#pdf_extensions = ['vectorpdf']
# Page template name for "regular" pages
#pdf_page_template = 'cutePage'
# Show Table Of Contents at the beginning?
# pdf_use_toc = True
# How many levels deep should the table of contents be?
pdf_toc_depth = 3
# Add section number to section references
# pdf_use_numbered_links = True
# Background images fitting mode
pdf_fit_background_mode = 'scale'
